print('Nume: Vrancean Vlad')
print('Data și locul nașterii: 23.11.2004 Bălți,Moldova ')
print('E-mail: vlad_vrancean@mail.ru')
print('Nr. de telefon: +37368620662')
print('Adresa de domiciliu: Colesov 7/8')
print('Naționalitate: moldovean')
print('Studii: Școala Primară "Spiridon Vangheli" 2010-2014,Liceul Teoretic "Mihai Eminescu"2014-2020')
print('Limbi străine: engleza-avansat,germana- începător')
print('Alte aptitudini: responsabil,ambițios')
print('Hobby:dansurile,volei')